### ISSUE TITLE
Dashboard rotation

### ISSUE THREAD

**Issue by Juyoo** [michelin/suricate#215]
### Subject of the issue
**- Backend:**
Add a new table "ProjectSlide" between Project -> ProjectWidget association.
So the new structure of a dashboard should be Project * ->n ProjectSlide *->n ProjectWidget

**- Frontend:**
In the frontend we should have these possibilities:
- Put on pause the rotation
- Switch manually the slides
- Switch automatically the slides (the time can be different for every slides)
- Update/add project and slides information

#### Issue type
[] Bug
[] Improvment
[] Documentation
[x] Feature

**NB**: Specify labels in right panel also

### Expected behaviour
Tell us what should happen

**Comment by yodamad** [comment]
@thibsign : Do you think u'll be able to close this issue by the end of the week ?
We plan to release soon & need to know if we can include it or postpone it
