### ISSUE TITLE
Super user can delete dashboards

### ISSUE THREAD

**Issue by Juyoo** [michelin/suricate#87]
### Subject of the issue
Let the possibility for the super user to delete a dashboard

Related to : Issue #86 

#### Issue type
[] Bug
[] Improvment
[] Documentation
[x] Feature

**Comment by janak1710** [comment]
@Juyoo - Hi, I'm a beginner to open source. I would like to contribute to this project. I was trying to setup my dev environment but Register Page comes blank with the registerForm as undefined in the RegisterComponent. It would be great if you could help me start up with this project.

**Comment by janak1710** [comment]
@Juyoo - I was able to setup my dev environment. Any guides on how to start working on this feature?

**Comment by yodamad** [comment]
Hi 

The idea is to add a button on dashboard page to call delete api for a dashboard

U have to check that current logged user is an Admin

To start u can have a look at user management page ans how we delete a User

**Comment by janak1710** [comment]
@yodamad - Hi, isn't this already implemented? Correct me if I'm wrong but you can delete dashboards from the dashboard page if an Admin is logged in.

**Comment by janak1710** [comment]
@Juyoo @yodamad - Did you guys have any issues setting up frontend on mac? It's unable to find/load Angular material ui core components.

**Comment by janak1710** [comment]
<img width="1359" alt="screen shot 2018-07-14 at 9 20 14 am" src="https://user-images.githubusercontent.com/16740229/42725300-3333a090-8747-11e8-9fa9-f1e57a281926.png">

It doesn't load the CSS. Using same node, npm, yarn and chrome version on the mac. Can you please help me with this?

**Comment by janak1710** [comment]
> Create a reference table with User, project_role, project as PK

@Juyoo - Should I create a new table for this or add a column for project roles in existing table `user_project` ?

**Comment by yodamad** [comment]
Would prefer a table it's more easily extensible for future potential needs

**Comment by janak1710** [comment]
@Juyoo @yodamad - I don't have access to push to this repo. How do I get access?

**Comment by yodamad** [comment]
You need to fork & pull request on our dev branch

**Comment by yodamad** [comment]
Hi @janak1710 , we plan to release this week a new version of Suricate. Are you still working on this issue ? If so, do you think we can include it for this release or postpone it to a future one ?

**Comment by yodamad** [comment]
@janak1710 any newz ?
